"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase-server";
import { deliverableSchema } from "@/lib/validation";
import { computeAndPersistReadiness } from "@/lib/readiness/service";

async function context(projectId:string){const supabase=await createSupabaseServerClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");const {data:project}=await supabase.from("projects").select("id,organization_id").eq("id",projectId).single();if(!project)redirect("/app/delivery");return {supabase,user,project};}
function back(id:string){redirect(`/app/delivery?project=${encodeURIComponent(id)}`);}

export async function createDeliverable(formData:FormData){
  const raw={projectId:String(formData.get("projectId")??""),name:String(formData.get("name")??""),type:String(formData.get("type")??"DOCUMENT"),criticality:String(formData.get("criticality")??"NORMAL"),dueDate:String(formData.get("dueDate")??""),acceptanceCriteria:String(formData.get("acceptanceCriteria")??"")};
  const parsed=deliverableSchema.safeParse(raw);if(!parsed.success)back(raw.projectId);
  const {supabase,user,project}=await context(parsed.data.projectId);
  const {data:d,error}=await supabase.from("deliverables").insert({project_id:project.id,name:parsed.data.name,type:parsed.data.type,criticality:parsed.data.criticality,due_date:parsed.data.dueDate||null,acceptance_criteria:parsed.data.acceptanceCriteria||null,owner_id:user.id}).select("id").single();
  if(error||!d)back(project.id);
  if(parsed.data.acceptanceCriteria)await supabase.from("acceptance_items").insert({project_id:project.id,deliverable_id:d.id,acceptance_criteria:parsed.data.acceptanceCriteria,status:"OPEN",evidence_required:true});
  await supabase.from("activity_log").insert({organization_id:project.organization_id,project_id:project.id,actor_id:user.id,action:"DELIVERABLE_CREATED",object_type:"deliverable",object_id:d.id});
  await computeAndPersistReadiness(supabase,project.id).catch(()=>null);revalidatePath("/app/delivery");back(project.id);
}

export async function linkRequirementDeliverable(formData:FormData){const projectId=String(formData.get("projectId")??"");const requirementId=String(formData.get("requirementId")??"");const deliverableId=String(formData.get("deliverableId")??"");const {supabase,user,project}=await context(projectId);const {error}=await supabase.from("requirement_deliverables").upsert({requirement_id:requirementId,deliverable_id:deliverableId},{onConflict:"requirement_id,deliverable_id"});if(!error)await supabase.from("activity_log").insert({organization_id:project.organization_id,project_id:project.id,actor_id:user.id,action:"REQUIREMENT_DELIVERABLE_LINKED",object_type:"requirement_deliverable",metadata:{requirementId,deliverableId}});await computeAndPersistReadiness(supabase,project.id).catch(()=>null);revalidatePath("/app/delivery");back(project.id);}

export async function addEvidence(formData:FormData){const projectId=String(formData.get("projectId")??"");const requirementId=String(formData.get("requirementId")??"");const {supabase,user,project}=await context(projectId);const {data:e,error}=await supabase.from("evidence").insert({project_id:projectId,requirement_id:requirementId,document_id:String(formData.get("documentId")??"")||null,type:String(formData.get("type")??"DOCUMENT")||"DOCUMENT",description:String(formData.get("description")??"")||null}).select("id").single();if(!error&&e)await supabase.from("activity_log").insert({organization_id:project.organization_id,project_id:project.id,actor_id:user.id,action:"EVIDENCE_ADDED",object_type:"evidence",object_id:e.id});await computeAndPersistReadiness(supabase,project.id).catch(()=>null);revalidatePath("/app/delivery");back(project.id);}

export async function setEvidenceVerification(formData:FormData){const projectId=String(formData.get("projectId")??"");const evidenceId=String(formData.get("evidenceId")??"");const status=String(formData.get("status")??"UNVERIFIED");const {supabase,user,project}=await context(projectId);await supabase.from("evidence").update({verification_status:status,verified_by:["VERIFIED","REJECTED"].includes(status)?user.id:null,verified_at:["VERIFIED","REJECTED"].includes(status)?new Date().toISOString():null}).eq("id",evidenceId).eq("project_id",projectId);await supabase.from("activity_log").insert({organization_id:project.organization_id,project_id:project.id,actor_id:user.id,action:`EVIDENCE_${status}`,object_type:"evidence",object_id:evidenceId});await computeAndPersistReadiness(supabase,project.id).catch(()=>null);revalidatePath("/app/delivery");revalidatePath("/app/projects/[id]", "page");back(project.id);}

export async function setVerification(formData:FormData){const projectId=String(formData.get("projectId")??"");const requirementId=String(formData.get("requirementId")??"");const method=String(formData.get("method")??"DOCUMENT_REVIEW");const status=String(formData.get("status")??"IN_PROGRESS");const {supabase,user,project}=await context(projectId);const {data:record,error}=await supabase.from("verification_records").upsert({project_id:projectId,requirement_id:requirementId,method,status,result:String(formData.get("result")??"")||null,performed_by:["PASSED","FAILED"].includes(status)?user.id:null,performed_at:["PASSED","FAILED"].includes(status)?new Date().toISOString():null},{onConflict:"requirement_id,method"}).select("id").single();if(!error&&record){await supabase.rpc("recalculate_requirement_status",{p_requirement_id:requirementId});await supabase.from("activity_log").insert({organization_id:project.organization_id,project_id:project.id,actor_id:user.id,action:`VERIFICATION_${status}`,object_type:"verification",object_id:record.id});}await computeAndPersistReadiness(supabase,project.id).catch(()=>null);revalidatePath("/app/delivery");revalidatePath("/app/requirements");back(project.id);}

export async function setAcceptance(formData:FormData){const projectId=String(formData.get("projectId")??"");const acceptanceId=String(formData.get("acceptanceId")??"");const status=String(formData.get("status")??"OPEN");const {supabase,user,project}=await context(projectId);await supabase.from("acceptance_items").update({status,accepted_by:status==="ACCEPTED"?user.id:null,accepted_at:status==="ACCEPTED"?new Date().toISOString():null}).eq("id",acceptanceId).eq("project_id",projectId);await supabase.from("activity_log").insert({organization_id:project.organization_id,project_id:project.id,actor_id:user.id,action:`ACCEPTANCE_${status}`,object_type:"acceptance_item",object_id:acceptanceId});await computeAndPersistReadiness(supabase,project.id).catch(()=>null);revalidatePath("/app/delivery");back(project.id);}

export async function recalculateReadiness(formData:FormData){const projectId=String(formData.get("projectId")??"");const {supabase}=await context(projectId);await computeAndPersistReadiness(supabase,projectId);revalidatePath("/app/delivery");revalidatePath(`/app/projects/${projectId}`);back(projectId);}
