import Link from "next/link";
import { createSupabaseServerClient } from "@/lib/supabase-server";
import { addEvidence, createDeliverable, linkRequirementDeliverable, recalculateReadiness, setAcceptance, setEvidenceVerification, setVerification } from "./actions";

export default async function DeliveryPage({ searchParams }: { searchParams: Promise<{ project?: string }> }) {
  const params=await searchParams;const supabase=await createSupabaseServerClient();const {data:projects}=await supabase.from("projects").select("id,name,code,target_delivery_date").order("created_at",{ascending:false});const projectId=params.project&&projects?.some(p=>p.id===params.project)?params.project:projects?.[0]?.id;
  if(!projectId)return <div className="content"><div className="empty">Create a project first.</div></div>;
  const project=projects!.find(p=>p.id===projectId)!;
  const [{data:reqs},{data:dels},{data:evs},{data:vers},{data:accs},{data:docs},{data:snapshots}]=await Promise.all([
    supabase.from("requirements").select("id,source_text,priority,status,human_review_status,verification_method").eq("project_id",projectId).order("created_at",{ascending:false}),
    supabase.from("deliverables").select("id,name,type,criticality,status,due_date,acceptance_criteria").eq("project_id",projectId).order("created_at",{ascending:false}),
    supabase.from("evidence").select("id,requirement_id,document_id,type,description,verification_status").eq("project_id",projectId).order("created_at",{ascending:false}),
    supabase.from("verification_records").select("id,requirement_id,method,status,result").eq("project_id",projectId).order("created_at",{ascending:false}),
    supabase.from("acceptance_items").select("id,deliverable_id,requirement_id,acceptance_criteria,status,evidence_required").eq("project_id",projectId).order("created_at",{ascending:false}),
    supabase.from("documents").select("id,name,current_revision").eq("project_id",projectId).order("created_at",{ascending:false}),
    supabase.from("readiness_snapshots").select("overall_score,delivery_status,blocker_count,calculated_at,explanation,requirement_score,deliverable_score,evidence_score,verification_score,acceptance_score").eq("project_id",projectId).order("calculated_at",{ascending:false}).limit(1),
  ]);
  const snap=snapshots?.[0];const approved=(reqs??[]).filter(r=>r.human_review_status==="APPROVED");const currentReqs=approved.length?approved:reqs??[];
  return <div className="content"><div className="page-header-row"><div><div className="eyebrow">{project.code}</div><h1 className="page-title">Delivery readiness</h1><p className="page-subtitle">{project.name} · target {project.target_delivery_date??"not set"}</p></div><div className="button-row"><form action={recalculateReadiness}><input type="hidden" name="projectId" value={projectId}/><button className="btn">Recalculate</button></form><a className="btn" href={`/api/export?project=${projectId}`}>Export package</a></div></div><div className="readiness-hero"><div><div className="metric-label">Current readiness</div><div className="readiness-number">{snap?.overall_score??0}%</div><span className={`badge ${snap?.delivery_status==="BLOCKED"?"badge-red":snap?.delivery_status==="AT_RISK"?"badge-yellow":snap?.delivery_status==="READY"?"badge-green":"badge-gray"}`}>{(snap?.delivery_status??"ON_TRACK").replaceAll("_"," ")}</span></div><div className="readiness-explain"><div className="metric-label">Dimensions</div><div className="score-grid">{[["Requirements",snap?.requirement_score??0],["Deliverables",snap?.deliverable_score??0],["Evidence",snap?.evidence_score??0],["Verification",snap?.verification_score??0],["Acceptance",snap?.acceptance_score??0]].map(([n,v])=><div key={String(n)}><span>{n}</span><strong>{v}%</strong></div>)}</div></div></div>
  <div className="grid grid-2" style={{marginTop:18}}><section className="card"><div className="section-head"><h2>Blockers</h2><span className="badge badge-gray">{snap?.blocker_count??0}</span></div>{Array.isArray(snap?.explanation?.blockers)&&snap.explanation.blockers.length?<div className="stack">{snap.explanation.blockers.map((b:any,i:number)=><div className="blocker" key={i}><span className={`badge ${b.severity==="P0"?"badge-red":"badge-yellow"}`}>{b.severity}</span><div><strong>{b.title}</strong><div className="metric-note">{b.detail}</div></div></div>)}</div>:<div className="empty">No blockers detected.</div>}</section><section className="card"><div className="section-head"><h2>Workflow</h2></div><div className="flow"><span>Requirement</span><b>→</b><span>Deliverable</span><b>→</b><span>Evidence</span><b>→</b><span>Verification</span><b>→</b><span>Acceptance</span></div></section></div>
  <section className="card" style={{marginTop:18}}><div className="section-head"><h2>Deliverables</h2></div><form action={createDeliverable} className="form wide-form"><input type="hidden" name="projectId" value={projectId}/><div className="grid grid-2"><label>Name<input name="name" required placeholder="Technical drawing package"/></label><label>Type<input name="type" defaultValue="DOCUMENT"/></label></div><div className="grid grid-2"><label>Criticality<select name="criticality" className="select"><option>CRITICAL</option><option>HIGH</option><option>NORMAL</option></select></label><label>Due date<input name="dueDate" type="date"/></label></div><label>Acceptance criteria<textarea name="acceptanceCriteria" rows={2}/></label><button className="btn btn-primary">Create deliverable</button></form>{dels?.length?<table className="table table-spaced"><thead><tr><th>Deliverable</th><th>Criticality</th><th>Status</th><th>Due</th></tr></thead><tbody>{dels.map(d=><tr key={d.id}><td><strong>{d.name}</strong><div className="metric-note">{d.type}{d.acceptance_criteria?` · ${d.acceptance_criteria}`:""}</div></td><td>{d.criticality}</td><td>{d.status}</td><td>{d.due_date??"—"}</td></tr>)}</tbody></table>:null}</section>
  <section className="card" style={{marginTop:18}}><div className="section-head"><h2>Requirement → deliverable links</h2></div>{currentReqs.length&&dels?.length?<form action={linkRequirementDeliverable} className="form wide-form"><input type="hidden" name="projectId" value={projectId}/><div className="grid grid-2"><label>Requirement<select name="requirementId" className="select">{currentReqs.map(r=><option key={r.id} value={r.id}>{r.priority} · {r.source_text.slice(0,90)}</option>)}</select></label><label>Deliverable<select name="deliverableId" className="select">{dels.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label></div><button className="btn btn-primary">Link</button></form>:<div className="empty">Approve requirements and create deliverables first.</div>}</section>
  <section className="card" style={{marginTop:18}}><div className="section-head"><h2>Evidence & verification</h2></div>{currentReqs.length?<div className="stack">{currentReqs.map(r=>{const re=(evs??[]).filter(e=>e.requirement_id===r.id);const rv=(vers??[]).filter(v=>v.requirement_id===r.id);return <div className="workflow-card" key={r.id}><div className="workflow-title"><div><span className={`badge ${r.priority==="CRITICAL"?"badge-red":r.priority==="HIGH"?"badge-yellow":"badge-gray"}`}>{r.priority}</span><p>{r.source_text}</p></div><span className="badge badge-gray">{r.status}</span></div><div className="grid grid-2"><div><div className="metric-label">Evidence</div><form action={addEvidence} className="form wide-form compact-form"><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="requirementId" value={r.id}/><div className="grid grid-2"><input name="type" defaultValue="DOCUMENT"/><select name="documentId" className="select"><option value="">No document</option>{docs?.map(d=><option key={d.id} value={d.id}>{d.name} Rev {d.current_revision}</option>)}</select></div><input name="description" placeholder="Evidence description"/><button className="btn">Add evidence</button></form>{re.map(e=><div className="evidence-row" key={e.id}><span>{e.type}</span><span>{e.verification_status}</span>{e.description?<span>{e.description}</span>:null}<form action={setEvidenceVerification}><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="evidenceId" value={e.id}/><input type="hidden" name="status" value="VERIFIED"/><button className="btn btn-mini">Verify</button></form></div>)}</div><div><div className="metric-label">Verification</div><form action={setVerification} className="form wide-form compact-form"><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="requirementId" value={r.id}/><div className="grid grid-2"><select name="method" className="select" defaultValue={r.verification_method??"DOCUMENT_REVIEW"}><option>DOCUMENT_REVIEW</option><option>TEST</option><option>INSPECTION</option><option>CERTIFICATE</option><option>ANALYSIS</option><option>DEMONSTRATION</option></select><select name="status" className="select" defaultValue={rv[0]?.status??"IN_PROGRESS"}><option>IN_PROGRESS</option><option>PASSED</option><option>FAILED</option></select></div><input name="result" defaultValue={rv[0]?.result??""} placeholder="Result / notes"/><button className="btn">Save verification</button></form>{rv.map(v=><div className="metric-note" key={v.id}>{v.method} · {v.status}{v.result?` · ${v.result}`:""}</div>)}</div></div></div>})}</div>:<div className="empty">Approve requirements first.</div>}</section>
  <section className="card" style={{marginTop:18}}><div className="section-head"><h2>Acceptance</h2></div>{accs?.length?<table className="table"><thead><tr><th>Criteria</th><th>Status</th><th>Actions</th></tr></thead><tbody>{accs.map(a=><tr key={a.id}><td>{a.acceptance_criteria}</td><td>{a.status}</td><td><div className="button-row"><form action={setAcceptance}><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="acceptanceId" value={a.id}/><input type="hidden" name="status" value="ACCEPTED"/><button className="btn btn-primary">Accept</button></form><form action={setAcceptance}><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="acceptanceId" value={a.id}/><input type="hidden" name="status" value="REJECTED"/><button className="btn btn-danger">Reject</button></form></div></td></tr>)}</tbody></table>:<div className="empty">Acceptance items appear when a deliverable has acceptance criteria.</div>}</section>
  </div>;
}
