import Link from "next/link";
import { createSupabaseServerClient } from "@/lib/supabase-server";
import { reviewRequirement } from "./actions";

export default async function RequirementsPage({ searchParams }: { searchParams: Promise<{ project?: string }> }) {
  const params = await searchParams;
  const supabase = await createSupabaseServerClient();
  const { data: projects } = await supabase.from("projects").select("id,name,code").order("created_at", { ascending: false });
  const selected = params.project && projects?.some(p => p.id === params.project) ? params.project : projects?.[0]?.id;
  const { data: requirements } = selected ? await supabase.from("requirements").select("id,source_text,source_page,category,priority,status,human_review_status,ai_confidence,due_date").eq("project_id", selected).order("created_at", { ascending: false }).limit(250) : { data: [] };
  return <div className="content"><div className="page-header-row"><div><h1 className="page-title">Requirements</h1><p className="page-subtitle">AI-extracted obligations remain drafts until a human approves them.</p></div>{selected ? <Link className="btn btn-primary" href={`/app/delivery?project=${selected}`}>Delivery view</Link> : null}</div>{projects?.length ? <div className="card" style={{marginBottom:18}}><form method="get"><label>Project<select className="select" name="project" defaultValue={selected}>{projects.map(p=><option value={p.id} key={p.id}>{p.code} — {p.name}</option>)}</select></label><button className="btn" style={{marginTop:8}}>Open</button></form></div> : null}<section className="card">{requirements?.length ? <div className="table-wrap"><table className="table"><thead><tr><th>Requirement</th><th>Priority</th><th>AI confidence</th><th>Review</th><th>Status</th></tr></thead><tbody>{requirements.map(r=><tr key={r.id}><td style={{minWidth:460}}><div>{r.source_text}</div><div className="metric-note">{r.category || "Uncategorized"} · {r.source_page ? `p.${r.source_page}` : "page not mapped"}{r.due_date ? ` · due ${r.due_date}` : ""}</div></td><td><span className={`badge ${r.priority === "CRITICAL" ? "badge-red" : r.priority === "HIGH" ? "badge-yellow" : "badge-gray"}`}>{r.priority}</span></td><td>{r.ai_confidence == null ? "—" : `${Math.round(Number(r.ai_confidence)*100)}%`}</td><td>{r.human_review_status === "PENDING" ? <div className="button-row"><form action={reviewRequirement}><input type="hidden" name="requirementId" value={r.id}/><input type="hidden" name="decision" value="APPROVED"/><button className="btn btn-primary">Approve</button></form><form action={reviewRequirement}><input type="hidden" name="requirementId" value={r.id}/><input type="hidden" name="decision" value="REJECTED"/><button className="btn">Reject</button></form></div> : <span className={`badge ${r.human_review_status === "APPROVED" ? "badge-green" : "badge-red"}`}>{r.human_review_status}</span>}</td><td>{r.status}</td></tr>)}</tbody></table></div> : <div className="empty">No requirements in this project yet. Upload a source contract PDF.</div>}</section></div>;
}
